/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package proga_lab_5

import proga_lab_5.commands.*


val operator = Operator()
val commandManager = CommandManager()
fun main() {

    commandManager.register(Exit(), Help(), Info(), Show(), Save(), Sort() ,ExecuteScript(), PrintAscending(), FilterContainsName(), Clear(),
        RemoveAllByMetersAboveSeaLevel(), RemoveById(), RemoveLower(), RemoveAt(), UpdateById(), Add())

    operator.process()


}


